import "../styles/global.scss";
import { Header } from "../components/Header";
import { Roboto } from "next/font/google";

const roboto = Roboto({
	subsets: ["latin"],
	weight: ["400", "700", "900"],
});

export const metadata = {
	title: "Ig News | home",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.png" type="image/png" />
			</head>
			<body className={roboto.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
