export const metadata = {
	title: "Ig News | products",
	description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
